import { nanoid } from 'nanoid';
import type {
  UserProfile,
  Trophy,
  ChatThread,
  Message,
  TournamentPoster,
  Notification,
  Friendship,
} from '@shared/types';

export const currentUserId = 'user-current-123';

export const seedProfiles: UserProfile[] = [
  {
    id: currentUserId,
    username: 'you',
    displayName: 'You (Test User)',
    avatarUri: 'https://i.pravatar.cc/150?img=1',
    bio: 'Passionate gamer and tournament enthusiast. Always up for a challenge!',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-alice-456',
    username: 'alice_pro',
    displayName: 'Alice Johnson',
    avatarUri: 'https://i.pravatar.cc/150?img=5',
    bio: 'Professional Valorant player. 3x tournament champion.',
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
  },
  {
    id: 'user-bob-789',
    username: 'bob_gamer',
    displayName: 'Bob Smith',
    avatarUri: 'https://i.pravatar.cc/150?img=12',
    bio: 'CS:GO enthusiast. Love organizing community events!',
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
  },
  {
    id: 'user-carol-101',
    username: 'carol_wins',
    displayName: 'Carol Martinez',
    avatarUri: 'https://i.pravatar.cc/150?img=9',
    bio: 'Tournament organizer and streamer. Follow me on Twitch!',
    createdAt: new Date(Date.now() - 86400000 * 45).toISOString(),
  },
];

export const seedFriendships: Friendship[] = [
  {
    id: nanoid(),
    user1Id: currentUserId,
    user2Id: 'user-alice-456',
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
  },
  {
    id: nanoid(),
    user1Id: currentUserId,
    user2Id: 'user-bob-789',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
];

export const seedTrophies: Trophy[] = [
  {
    id: nanoid(),
    userId: currentUserId,
    tournamentId: 'tournament-1',
    title: '🏆 Spring Champion',
    description: '1st Place in Spring Tournament 2024',
    iconUrl: '🏆',
    awardedBy: 'Tournament Admin',
    awardedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: nanoid(),
    userId: currentUserId,
    tournamentId: 'tournament-2',
    title: '🥈 Runner Up',
    description: '2nd Place in Summer Championship',
    iconUrl: '🥈',
    awardedBy: 'Carol Martinez',
    awardedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: nanoid(),
    userId: currentUserId,
    tournamentId: 'tournament-3',
    title: '🎯 Perfect Aim',
    description: 'Best accuracy award in Valorant Cup',
    iconUrl: '🎯',
    awardedBy: 'Alice Johnson',
    awardedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];

export const seedChatThreads: ChatThread[] = [
  {
    id: 'thread-1',
    type: 'group',
    name: 'Tournament Organizers',
    avatarUri: 'https://i.pravatar.cc/150?img=20',
    participantIds: [currentUserId, 'user-alice-456', 'user-bob-789', 'user-carol-101'],
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'thread-2',
    type: 'direct',
    participantIds: [currentUserId, 'user-alice-456'],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'thread-3',
    type: 'group',
    name: 'Valorant Squad',
    avatarUri: 'https://i.pravatar.cc/150?img=25',
    participantIds: [currentUserId, 'user-alice-456', 'user-bob-789'],
    createdAt: new Date(Date.now() - 86400000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const seedMessages: Message[] = [
  {
    id: nanoid(),
    threadId: 'thread-1',
    senderId: 'user-carol-101',
    content: 'Hey everyone! The next tournament is scheduled for next weekend.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    readBy: [currentUserId, 'user-alice-456'],
  },
  {
    id: nanoid(),
    threadId: 'thread-1',
    senderId: 'user-alice-456',
    content: 'Sounds great! Count me in.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    readBy: [currentUserId],
  },
  {
    id: nanoid(),
    threadId: 'thread-2',
    senderId: 'user-alice-456',
    content: 'Good game yesterday! Your Jett plays were insane.',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    readBy: [currentUserId],
  },
  {
    id: nanoid(),
    threadId: 'thread-2',
    senderId: currentUserId,
    content: 'Thanks! You were amazing too. Let\'s team up for the next one.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    readBy: ['user-alice-456'],
  },
];

export const seedTournaments: TournamentPoster[] = [
  {
    id: 'tournament-upcoming-1',
    name: 'Valorant Champions Cup 2024',
    game: 'Valorant',
    imageUrl: '/attached_assets/stock_images/valorant_esports_cha_a54c6cb2.jpg',
    format: 'single_elimination',
    prizeReward: '$5,000',
    entryFee: 500,
    organizerId: 'user-carol-101',
    organizerName: 'Carol Martinez',
    maxTeams: 16,
    currentTeams: 8,
    startDate: new Date(Date.now() + 86400000 * 7).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-2',
    name: 'CS:GO Pro League',
    game: 'CS:GO',
    imageUrl: '/attached_assets/stock_images/counter_strike_csgo__b6102c0a.jpg',
    format: 'round_robin',
    prizeReward: '$10,000',
    entryFee: 1000,
    organizerId: 'user-bob-789',
    organizerName: 'Bob Smith',
    maxTeams: 12,
    currentTeams: 10,
    startDate: new Date(Date.now() + 86400000 * 14).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-in-progress-1',
    name: 'League of Legends Spring Split',
    game: 'League of Legends',
    imageUrl: '/attached_assets/stock_images/league_of_legends_es_56c6b74b.jpg',
    format: 'swiss',
    prizeReward: '$15,000',
    entryFee: 1200,
    organizerId: 'user-alice-456',
    organizerName: 'Alice Johnson',
    maxTeams: 20,
    currentTeams: 20,
    startDate: new Date(Date.now() - 86400000 * 2).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-3',
    name: 'Apex Legends Battle Royale',
    game: 'Apex Legends',
    imageUrl: '/attached_assets/stock_images/apex_legends_battle__899cf222.jpg',
    format: 'single_elimination',
    prizeReward: '$3,000',
    entryFee: 250,
    organizerId: 'user-carol-101',
    organizerName: 'Carol Martinez',
    maxTeams: 32,
    currentTeams: 15,
    startDate: new Date(Date.now() + 86400000 * 21).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-4',
    name: 'Fortnite Championship',
    game: 'Fortnite',
    imageUrl: '/attached_assets/stock_images/fortnite_battle_roya_6be8cfb7.jpg',
    format: 'single_elimination',
    prizeReward: '$8,000',
    entryFee: 750,
    organizerId: 'user-alice-456',
    organizerName: 'Alice Johnson',
    maxTeams: 24,
    currentTeams: 18,
    startDate: new Date(Date.now() + 86400000 * 10).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-5',
    name: 'Rocket League Masters',
    game: 'Rocket League',
    imageUrl: '/attached_assets/stock_images/rocket_league_esport_503d8de2.jpg',
    format: 'round_robin',
    prizeReward: '$6,500',
    entryFee: 600,
    organizerId: 'user-bob-789',
    organizerName: 'Bob Smith',
    maxTeams: 16,
    currentTeams: 12,
    startDate: new Date(Date.now() + 86400000 * 18).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-6',
    name: 'Overwatch Invitational',
    game: 'Overwatch',
    imageUrl: '/attached_assets/stock_images/overwatch_esports_co_0b995362.jpg',
    format: 'single_elimination',
    prizeReward: '$7,200',
    entryFee: 650,
    organizerId: 'user-carol-101',
    organizerName: 'Carol Martinez',
    maxTeams: 20,
    currentTeams: 14,
    startDate: new Date(Date.now() + 86400000 * 25).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-7',
    name: 'PUBG Mobile Showdown',
    game: 'PUBG Mobile',
    imageUrl: '/attached_assets/stock_images/pubg_mobile_battle_r_e0cdd485.jpg',
    format: 'swiss',
    prizeReward: '$4,500',
    entryFee: 400,
    organizerId: 'user-alice-456',
    organizerName: 'Alice Johnson',
    maxTeams: 28,
    currentTeams: 20,
    startDate: new Date(Date.now() + 86400000 * 12).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-8',
    name: 'Rainbow Six Siege Cup',
    game: 'Rainbow Six Siege',
    imageUrl: '/attached_assets/stock_images/rainbow_six_siege_ta_08a7ae9d.jpg',
    format: 'single_elimination',
    prizeReward: '$9,000',
    entryFee: 800,
    organizerId: 'user-bob-789',
    organizerName: 'Bob Smith',
    maxTeams: 16,
    currentTeams: 11,
    startDate: new Date(Date.now() + 86400000 * 16).toISOString(),
    status: 'upcoming',
  },
  {
    id: 'tournament-upcoming-9',
    name: 'FIFA Ultimate Championship',
    game: 'FIFA',
    imageUrl: '/attached_assets/generated_images/FIFA_tournament_poster_caed26a8.png',
    format: 'single_elimination',
    prizeReward: '$500',
    entryFee: 50,
    organizerId: 'user-carol-101',
    organizerName: 'Carol Martinez',
    maxTeams: 32,
    currentTeams: 24,
    startDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    status: 'upcoming',
  },
];

export const seedNotifications: Notification[] = [
  {
    id: nanoid(),
    userId: currentUserId,
    type: 'message',
    title: 'New Message from Alice Johnson',
    body: 'Good game yesterday! Your Jett plays were insane.',
    data: { threadId: 'thread-2' },
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: nanoid(),
    userId: currentUserId,
    type: 'friend_request',
    title: 'New Friend Request',
    body: 'David Lee sent you a friend request',
    data: { userId: 'user-david-999' },
    isRead: false,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: nanoid(),
    userId: currentUserId,
    type: 'tournament_invite',
    title: 'Tournament Invitation',
    body: 'You have been invited to Valorant Champions Cup 2024',
    data: { tournamentId: 'tournament-upcoming-1' },
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];
